#############################################################################
# Makefile for building: OpenGL-FreeType
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  OpenGL-FreeType.pro
# Template: app
# Command: /home/delexus/Qt5.3.2/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile OpenGL-FreeType.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++ -I. -I../../Qt5.3.2/5.3/gcc_64/include -I../../Qt5.3.2/5.3/gcc_64/include/QtWidgets -I../../Qt5.3.2/5.3/gcc_64/include/QtGui -I../../Qt5.3.2/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/delexus/Qt5.3.2/5.3/gcc_64 -Wl,-rpath,/home/delexus/Qt5.3.2/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -lfreetype -L/home/delexus/Qt5.3.2/5.3/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/delexus/Qt5.3.2/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		openglwindow.cpp qrc_shaders.cpp \
		moc_openglwindow.cpp
OBJECTS       = main.o \
		openglwindow.o \
		qrc_shaders.o \
		moc_openglwindow.o
DIST          = ../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/uic.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf \
		OpenGL-FreeType.pro main.cpp \
		openglwindow.cpp
QMAKE_TARGET  = OpenGL-FreeType
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = OpenGL-FreeType


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OpenGL-FreeType.pro ../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/uic.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf \
		OpenGL-FreeType.pro \
		shaders.qrc \
		/home/delexus/Qt5.3.2/5.3/gcc_64/lib/libQt5Widgets.prl \
		/home/delexus/Qt5.3.2/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/delexus/Qt5.3.2/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile OpenGL-FreeType.pro
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resources.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/moc.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/uic.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf:
OpenGL-FreeType.pro:
shaders.qrc:
/home/delexus/Qt5.3.2/5.3/gcc_64/lib/libQt5Widgets.prl:
/home/delexus/Qt5.3.2/5.3/gcc_64/lib/libQt5Gui.prl:
/home/delexus/Qt5.3.2/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile OpenGL-FreeType.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/OpenGL-FreeType1.0.0 || mkdir -p .tmp/OpenGL-FreeType1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/OpenGL-FreeType1.0.0/ && $(COPY_FILE) --parents shaders.qrc .tmp/OpenGL-FreeType1.0.0/ && $(COPY_FILE) --parents openglwindow.h .tmp/OpenGL-FreeType1.0.0/ && $(COPY_FILE) --parents main.cpp openglwindow.cpp .tmp/OpenGL-FreeType1.0.0/ && (cd `dirname .tmp/OpenGL-FreeType1.0.0` && $(TAR) OpenGL-FreeType1.0.0.tar OpenGL-FreeType1.0.0 && $(COMPRESS) OpenGL-FreeType1.0.0.tar) && $(MOVE) `dirname .tmp/OpenGL-FreeType1.0.0`/OpenGL-FreeType1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OpenGL-FreeType1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_shaders.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_shaders.cpp
qrc_shaders.cpp: shaders.qrc \
		fshader.fsh \
		vshader.vsh
	/home/delexus/Qt5.3.2/5.3/gcc_64/bin/rcc -name shaders shaders.qrc -o qrc_shaders.cpp

compiler_moc_header_make_all: moc_openglwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_openglwindow.cpp
moc_openglwindow.cpp: ../../Qt5.3.2/5.3/gcc_64/include/QtGui/QWindow \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindow.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QObject \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QEvent \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QMargins \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QRect \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qsurface.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLFunctions \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qt_windows.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglcontext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QScopedPointer \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLContext \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector3d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector4d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qquaternion.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLBuffer \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLTexture \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengltexture.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		openglwindow.h
	/home/delexus/Qt5.3.2/5.3/gcc_64/bin/moc $(DEFINES) -I/home/delexus/Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++ -I/home/delexus/qtproject/OpenGL-FreeType -I/home/delexus/Qt5.3.2/5.3/gcc_64/include -I/home/delexus/Qt5.3.2/5.3/gcc_64/include/QtWidgets -I/home/delexus/Qt5.3.2/5.3/gcc_64/include/QtGui -I/home/delexus/Qt5.3.2/5.3/gcc_64/include/QtCore openglwindow.h -o moc_openglwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp openglwindow.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QWindow \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindow.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QObject \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QEvent \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QMargins \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QRect \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qsurface.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLFunctions \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qt_windows.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglcontext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QScopedPointer \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLContext \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector3d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector4d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qquaternion.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLBuffer \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLTexture \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengltexture.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QGuiApplication \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

openglwindow.o: openglwindow.cpp openglwindow.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QWindow \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindow.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QObject \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QEvent \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QMargins \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QRect \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qsurface.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLFunctions \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengl.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qt_windows.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglcontext.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QScopedPointer \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLContext \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector3d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qvector4d.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qquaternion.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLBuffer \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLTexture \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopengltexture.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		../../Qt5.3.2/5.3/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/QCoreApplication \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt5.3.2/5.3/gcc_64/include/QtCore/qeventloop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openglwindow.o openglwindow.cpp

qrc_shaders.o: qrc_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_shaders.o qrc_shaders.cpp

moc_openglwindow.o: moc_openglwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openglwindow.o moc_openglwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

